feat: add populate db
Snuffleevees-Paltanchez/back-mikbooks pull request #4
Opened 2024-06-12 16:07 UTC by BMarink512

### 🛠 Changes being made

- Add populate method at the endpoint db/populate; the method fetches the scraped data and inserts it into the DB. The method takes 3-4 minutes to run and finish

- Add base model schemas

- Add findOrCreate service on author, price, category, book, platform, and price

### ✨ What's the context?

### 📸 Screenshots (optional)

### 🏎 Quality check

- [X] Are your changes following SOLID principles?

- [ ] Are there any erroneous console logs, debuggers or leftover code in your changes?

- [X] Walk away, take a break, re-read what you filled out above does it make sense if you were coming in cold? What extra context could you provide?

2024-06-15 19:07 UTC, riadeane requested changes

2024-06-15 19:07 UTC, riadeane commented on prisma/schema.prisma
> +  raitings  Rating[]
dice 'raitings' y no 'ratings'

2024-06-15 19:07 UTC, riadeane commented on src/db/db.service.ts
> +      productUrl: data.link,
una pregunta, esto efectivamente actualiza los precios cuando tenemos un precio para un book y platform que ya existe?

2024-06-15 19:09 UTC, riadeane commented
Buen PR!! Solo ese typo y la duda que tengo

2024-06-15 21:07 UTC, BMarink512 commented on src/db/db.service.ts
> +      productUrl: data.link,
actualmente no esta implementado, pero al metodo del servicio seria agregar un update dentro de la llamada al upsert donde se actualice el precio y la fecha, lo agrego ahora

2024-06-16 00:32 UTC, riadeane approved these changes
Super!!

2024-06-16 00:36 UTC, AlfreMK commented
Please remember to do squash and merge to merge it

2024-06-16 00:46 UTC, merged